require('dotenv').config();
const express = require('express');
const cors = require('cors');
const { createClient } = require('@supabase/supabase-js');
const cron = require('node-cron');

const app = express();
app.use(cors());
app.use(express.json());

// Supabase
const supabase = createClient(
        process.env.SUPABASE_URL,
        process.env.SUPABASE_SERVICE_KEY
    );

// Routes
app.use('/api/ml', require('./routes/mercadolivre'));
app.use('/api/cj', require('./routes/cjdropshipping'));
app.use('/api/produtos', require('./routes/produtos'));
app.use('/api/pedidos', require('./routes/pedidos'));
app.use('/api/dashboard', require('./routes/dashboard'));

// Dashboard visual
app.get('/', async (req, res) => {
      try {
              const { data: tokens } = await supabase.from('ml_tokens').select('user_id, updated_at').limit(1);
              const { data: produtos } = await supabase.from('produtos').select('count').limit(1);
              const { data: pedidos } = await supabase.from('pedidos').select('*').order('created_at', { ascending: false }).limit(5);
              const { count: totalPedidos } = await supabase.from('pedidos').select('*', { count: 'exact', head: true });
              const { count: totalProdutos } = await supabase.from('produtos').select('*', { count: 'exact', head: true });
              const mlConectado = tokens && tokens.length > 0;
              const ultimaSync = tokens?.[0]?.updated_at ? new Date(tokens[0].updated_at).toLocaleString('pt-BR') : 'Nunca';
              const pedidosHtml = (pedidos || []).map(p => `
                    <tr>
                            <td>#${p.ml_order_id || '-'}</td>
                                    <td>${p.buyer_name || '-'}</td>
                                            <td>R$ ${(p.total || 0).toFixed(2)}</td>
                                                    <td><span class="badge ${p.status === 'paid' ? 'badge-success' : p.status === 'cancelled' ? 'badge-danger' : 'badge-warning'}">${p.status || '-'}</span></td>
                                                            <td>${p.created_at ? new Date(p.created_at).toLocaleDateString('pt-BR') : '-'}</td>
                                                                  </tr>`).join('') || '<tr><td colspan="5" style="text-align:center;color:#666">Nenhum pedido ainda</td></tr>';
              res.send(`<!DOCTYPE html>
              <html lang="pt-BR">
              <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>DropFacil - Dashboard</title>
              <style>
                * { margin: 0; padding: 0; box-sizing: border-box; }
                  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0f172a; color: #e2e8f0; min-height: 100vh; }
                    .header { background: linear-gradient(135deg, #1e40af 0%, #7c3aed 100%); padding: 20px 30px; display: flex; align-items: center; justify-content: space-between; box-shadow: 0 4px 20px rgba(0,0,0,0.3); }
                      .header h1 { font-size: 28px; font-weight: 800; color: white; letter-spacing: -0.5px; }
                        .header h1 span { color: #fbbf24; }
                          .status-pill { background: rgba(255,255,255,0.15); border: 1px solid rgba(255,255,255,0.3); border-radius: 20px; padding: 6px 16px; font-size: 13px; color: white; }
                            .status-dot { display: inline-block; width: 8px; height: 8px; border-radius: 50%; background: #4ade80; margin-right: 6px; animation: pulse 2s infinite; }
                              @keyframes pulse { 0%,100%{opacity:1} 50%{opacity:0.5} }
                                .container { max-width: 1200px; margin: 0 auto; padding: 30px 20px; }
                                  .cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin-bottom: 30px; }
                                    .card { background: #1e293b; border: 1px solid #334155; border-radius: 16px; padding: 24px; position: relative; overflow: hidden; }
                                      .card::before { content: ''; position: absolute; top: 0; left: 0; right: 0; height: 3px; }
                                        .card.blue::before { background: linear-gradient(90deg, #3b82f6, #60a5fa); }
                                          .card.green::before { background: linear-gradient(90deg, #10b981, #4ade80); }
                                            .card.orange::before { background: linear-gradient(90deg, #f59e0b, #fbbf24); }
                                              .card.purple::before { background: linear-gradient(90deg, #8b5cf6, #a78bfa); }
                                                .card-label { font-size: 12px; color: #64748b; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 8px; }
                                                  .card-value { font-size: 36px; font-weight: 800; color: white; }
                                                    .card-sub { font-size: 12px; color: #4ade80; margin-top: 4px; }
                                                      .section { background: #1e293b; border: 1px solid #334155; border-radius: 16px; padding: 24px; margin-bottom: 24px; }
                                                        .section h2 { font-size: 18px; font-weight: 700; color: #f1f5f9; margin-bottom: 20px; display: flex; align-items: center; gap: 10px; }
                                                          .integrations { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 16px; }
                                                            .integration { background: #0f172a; border: 1px solid #334155; border-radius: 12px; padding: 18px; display: flex; align-items: center; gap: 16px; }
                                                              .integration-icon { width: 48px; height: 48px; border-radius: 12px; display: flex; align-items: center; justify-content: center; font-size: 24px; }
                                                                .integration-info h3 { font-size: 14px; font-weight: 700; color: #f1f5f9; }
                                                                  .integration-info p { font-size: 12px; color: #64748b; margin-top: 2px; }
                                                                    .badge { padding: 3px 10px; border-radius: 20px; font-size: 11px; font-weight: 600; text-transform: uppercase; }
                                                                      .badge-success { background: #052e16; color: #4ade80; border: 1px solid #166534; }
                                                                        .badge-warning { background: #451a03; color: #fbbf24; border: 1px solid #92400e; }
                                                                          .badge-danger { background: #450a0a; color: #f87171; border: 1px solid #991b1b; }
                                                                            .badge-pending { background: #1e1b4b; color: #a78bfa; border: 1px solid #4c1d95; }
                                                                              table { width: 100%; border-collapse: collapse; }
                                                                                th { text-align: left; padding: 12px 16px; font-size: 12px; color: #64748b; text-transform: uppercase; letter-spacing: 1px; border-bottom: 1px solid #334155; }
                                                                                  td { padding: 14px 16px; font-size: 14px; border-bottom: 1px solid #1e293b; }
                                                                                    tr:hover td { background: #0f172a; }
                                                                                      .actions { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 12px; }
                                                                                        .btn { padding: 14px 20px; border-radius: 12px; font-size: 14px; font-weight: 600; cursor: pointer; border: none; transition: all 0.2s; text-align: center; }
                                                                                          .btn-primary { background: linear-gradient(135deg, #3b82f6, #2563eb); color: white; }
                                                                                            .btn-primary:hover { transform: translateY(-2px); box-shadow: 0 8px 25px rgba(59,130,246,0.4); }
                                                                                              .btn-success { background: linear-gradient(135deg, #10b981, #059669); color: white; }
                                                                                                .btn-success:hover { transform: translateY(-2px); box-shadow: 0 8px 25px rgba(16,185,129,0.4); }
                                                                                                  .btn-orange { background: linear-gradient(135deg, #f59e0b, #d97706); color: white; }
                                                                                                    .btn-orange:hover { transform: translateY(-2px); box-shadow: 0 8px 25px rgba(245,158,11,0.4); }
                                                                                                      .btn-purple { background: linear-gradient(135deg, #8b5cf6, #7c3aed); color: white; }
                                                                                                        .btn-purple:hover { transform: translateY(-2px); box-shadow: 0 8px 25px rgba(139,92,246,0.4); }
                                                                                                          #result { background: #0f172a; border: 1px solid #334155; border-radius: 12px; padding: 16px; margin-top: 16px; font-family: monospace; font-size: 13px; white-space: pre-wrap; max-height: 300px; overflow-y: auto; display: none; }
                                                                                                            .footer { text-align: center; padding: 20px; color: #334155; font-size: 13px; }
                                                                                                            </style>
                                                                                                            </head>
                                                                                                            <body>
                                                                                                            <div class="header">
                                                                                                              <h1>Drop<span>Facil</span> 🚀</h1>
                                                                                                                <div class="status-pill"><span class="status-dot"></span>Sistema Online</div>
                                                                                                                </div>
                                                                                                                <div class="container">
                                                                                                                  <div class="cards">
                                                                                                                      <div class="card blue">
                                                                                                                            <div class="card-label">Produtos Ativos</div>
                                                                                                                                  <div class="card-value">${totalProdutos || 0}</div>
                                                                                                                                        <div class="card-sub">no Mercado Livre</div>
                                                                                                                                            </div>
                                                                                                                                                <div class="card green">
                                                                                                                                                      <div class="card-label">Pedidos Totais</div>
                                                                                                                                                            <div class="card-value">${totalPedidos || 0}</div>
                                                                                                                                                                  <div class="card-sub">sincronizados</div>
                                                                                                                                                                      </div>
                                                                                                                                                                          <div class="card orange">
                                                                                                                                                                                <div class="card-label">ML Conectado</div>
                                                                                                                                                                                      <div class="card-value" style="font-size:28px">${mlConectado ? '✅ Sim' : '❌ Não'}</div>
                                                                                                                                                                                            <div class="card-sub">última sync: ${ultimaSync}</div>
                                                                                                                                                                                                </div>
                                                                                                                                                                                                    <div class="card purple">
                                                                                                                                                                                                          <div class="card-label">Automação</div>
                                                                                                                                                                                                                <div class="card-value" style="font-size:24px">⚡ Ativa</div>
                                                                                                                                                                                                                      <div class="card-sub">sync a cada 15 min</div>
                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                              <div class="section">
                                                                                                                                                                                                                                  <h2>🔗 Integrações</h2>
                                                                                                                                                                                                                                      <div class="integrations">
                                                                                                                                                                                                                                            <div class="integration">
                                                                                                                                                                                                                                                    <div class="integration-icon" style="background:#fff3cd">🛍️</div>
                                                                                                                                                                                                                                                            <div class="integration-info">
                                                                                                                                                                                                                                                                      <h3>Mercado Livre</h3>
                                                                                                                                                                                                                                                                                <p>Patrick Luan · ID: 3421636550</p>
                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                <span class="badge ${mlConectado ? 'badge-success' : 'badge-danger'}">${mlConectado ? 'Ativo' : 'Inativo'}</span>
                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                            <div class="integration">
                                                                                                                                                                                                                                                                                                                    <div class="integration-icon" style="background:#fff0e6">📦</div>
                                                                                                                                                                                                                                                                                                                            <div class="integration-info">
                                                                                                                                                                                                                                                                                                                                      <h3>CJ Dropshipping</h3>
                                                                                                                                                                                                                                                                                                                                                <p>CJ5445478 · pklalmeida@hotmail.com</p>
                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                <span class="badge badge-warning" id="cj-status">Verificando...</span>
                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                            <div class="integration">
                                                                                                                                                                                                                                                                                                                                                                                    <div class="integration-icon" style="background:#f0f0f0">🍊</div>
                                                                                                                                                                                                                                                                                                                                                                                            <div class="integration-info">
                                                                                                                                                                                                                                                                                                                                                                                                      <h3>Shopee</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                <p>techdropbrasil · Em aprovação</p>
                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                <span class="badge badge-pending">Aguardando</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <div class="section">
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h2>⚡ Ações Rápidas</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div class="actions">
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button class="btn btn-success" onclick="buscarMaisVendidos()">🔥 Buscar Mais Vendidos CJ</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button class="btn btn-primary" onclick="syncPedidos()">🔄 Sincronizar Pedidos ML</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button class="btn btn-orange" onclick="verProdutos()">📋 Ver Produtos Ativos</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button class="btn btn-purple" onclick="testarCJ()">🧪 Testar Auth CJ</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div id="result"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div class="section">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2>📦 Últimos Pedidos</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <thead><tr><th>Pedido ML</th><th>Comprador</th><th>Valor</th><th>Status</th><th>Data</th></tr></thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <tbody>${pedidosHtml}</tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="footer">DropFacil v1.0 · Sistema de Dropshipping Automatizado · Patrick Luan</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    async function mostrarResultado(data) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const el = document.getElementById('result');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        el.style.display = 'block';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          el.textContent = JSON.stringify(data, null, 2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          async function testarCJ() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mostrarResultado({loading: 'Testando autenticação CJ...'});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const r = await fetch('/api/cj/test');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const d = await r.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          mostrarResultado(d);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              document.getElementById('cj-status').textContent = d.success ? 'Ativo' : 'Erro';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  document.getElementById('cj-status').className = 'badge ' + (d.success ? 'badge-success' : 'badge-danger');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch(e) { mostrarResultado({error: e.message}); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    async function buscarMaisVendidos() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      mostrarResultado({loading: 'Buscando produtos mais vendidos...'});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const r = await fetch('/api/cj/mais-vendidos');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const d = await r.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mostrarResultado(d);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch(e) { mostrarResultado({error: e.message}); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      async function syncPedidos() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        mostrarResultado({loading: 'Sincronizando pedidos...'});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const r = await fetch('/api/dashboard/sync');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const d = await r.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      mostrarResultado(d);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setTimeout(() => location.reload(), 2000);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch(e) { mostrarResultado({error: e.message}); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            async function verProdutos() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              mostrarResultado({loading: 'Carregando produtos...'});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const r = await fetch('/api/produtos');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const d = await r.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mostrarResultado(d);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } catch(e) { mostrarResultado({error: e.message}); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Auto-test CJ on load
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              window.onload = () => testarCJ();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </html>`);
      } catch(e) {
              res.send('<h1>DropFacil Backend Online</h1><p>Erro ao carregar dashboard: ' + e.message + '</p>');
      }
});

// ML OAuth callback
app.get('/callback', async (req, res) => {
      const { code } = req.query;
      if (!code) return res.status(400).json({ error: 'Code missing' });
      try {
              const axios = require('axios');
              const response = await axios.post(
                        `https://api.mercadolibre.com/oauth/token`,
                        new URLSearchParams({
                                    grant_type: 'authorization_code',
                                    client_id: process.env.ML_APP_ID,
                                    client_secret: process.env.ML_CLIENT_SECRET,
                                    code,
                                    redirect_uri: process.env.ML_REDIRECT_URI
                        }),
                  { headers: { 'Content-Type': 'application/x-www-form-urlencoded' } }
                      );
              const { access_token, refresh_token, user_id } = response.data;
              await supabase.from('ml_tokens').upsert({
                        user_id: user_id.toString(),
                        access_token,
                        refresh_token,
                        updated_at: new Date().toISOString()
              });
              res.send('<html><body style="font-family:sans-serif;text-align:center;padding:50px;background:#0f172a;color:white"><h1>✅ Mercado Livre Conectado!</h1><p>Sua conta foi vinculada com sucesso.</p><a href="/" style="color:#60a5fa">← Voltar ao Dashboard</a></body></html>');
      } catch (err) {
              res.status(500).json({ error: err.response?.data || err.message });
      }
});

// Cron: sync orders every 15 min
cron.schedule('*/15 * * * *', async () => {
      console.log('[CRON] Sincronizando pedidos ML...');
      try {
              const axios = require('axios');
              const { data: tokens } = await supabase.from('ml_tokens').select('*');
              for (const token of tokens || []) {
                        const res = await axios.get(
                                    `https://api.mercadolibre.com/orders/search?seller=${token.user_id}&sort=date_desc&limit=10`,
                            { headers: { Authorization: `Bearer ${token.access_token}` } }
                                  );
                        const orders = res.data.results || [];
                        for (const order of orders) {
                                    await supabase.from('pedidos').upsert({
                                                  ml_order_id: order.id.toString(),
                                                  status: order.status,
                                                  total: order.total_amount,
                                                  buyer_name: order.buyer?.nickname,
                                                  created_at: order.date_created,
                                                  updated_at: new Date().toISOString()
                                    }, { onConflict: 'ml_order_id' });
                        }
              }
              console.log('[CRON] Pedidos sincronizados!');
      } catch (e) {
              console.error('[CRON] Erro:', e.message);
      }
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`DropFacil Backend rodando na porta ${PORT}`));
